# Generated by Django 5.0.1 on 2024-01-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctions_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='starting_bids',
            field=models.FloatField(default=0),
        ),
    ]
