# Generated by Django 5.0.1 on 2024-01-08 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctions_starting_bids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctions',
            old_name='starting_bids',
            new_name='starting_bid',
        ),
    ]
