# Generated by Django 5.0.1 on 2024-01-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_starting_bids_auctions_starting_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctions',
            old_name='starting_bid',
            new_name='bid',
        ),
        migrations.AlterField(
            model_name='auctions',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
