# Generated by Django 5.0.1 on 2024-01-10 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_starting_bid_auctions_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='username',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
