# Generated by Django 5.0.1 on 2024-01-10 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auctions_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctions',
            old_name='username',
            new_name='user',
        ),
    ]
