# Generated by Django 5.0.1 on 2024-01-11 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_bids_amount_bids_auction_bids_bidder_bids_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='auction',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.auctions'),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
