# Generated by Django 5.0.1 on 2024-01-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='category',
            field=models.CharField(choices=[('N/A', 'None'), ('CL', 'Clothing'), ('BO', 'Books'), ('MMG', 'Movies, Music & Games'), ('EL', 'Electronics'), ('HO', 'Home'), ('BE', 'Beauty & Health'), ('SP', 'Sports & Outdoors'), ('AU', 'Automotive & Industrial')], default='N/A', max_length=3),
        ),
    ]
